### ISSUE TITLE
Ecoportal - Ontoportal code alignement : UI  Road map 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [lifewatch-eric/ecoportal_web_ui#16]
### Context

The subcontracting is being accepted and signed to align the Ecoportal code with AgroPortal and OntoPortal by August 2023. The proposed roadmap includes extracting and saving newly implemented features, resetting code to the current release of Agroportal, re-integrating the features, and deploying and connecting the O'FAIRE service. 

This issue lists the steps (PRs) to achieve that for the UI and will be used to follow up on the project.

All the changes will be made in an isolated branch #1, tested and deployed first in https://ecoportal.lifewatchdev.eu/

### TODO

- [x] https://github.com/lifewatch-eric/ecoportal_web_ui/pull/15/
- [x] #2 
- [x] #3 
- [x] #4 
- [x] #5 
- [x] #6 
- [x] #20 
- [x] #8 
- [x] #9 
- [x] #10 
- [x] #11 
- [x] #12 
- [x] #13 
- [x] https://github.com/lifewatch-eric/ecoportal_web_ui/pull/17
- [x] #14
- [x] https://github.com/lifewatch-eric/ecoportal_web_ui/pull/18
- [x] https://github.com/lifewatch-eric/ecoportal_web_ui/pull/21

**Comment by syphax-bouazzouni** [comment]
Done and Deployed to production
